var regions = [
  "Andrast",
  "Anfalas",
  "Angmar",
  "Arnor",
  "Ash Mountains",
  "Barad-dûr",
  "Bree",
  "Buckland",
  "Cardolan",
  "Carrock",
  "Dagorlad",
  "Dale",
  "Dead Marshes",
  "Dimrill Dale",
  "Dol Amroth",
  "Dol Guldur",
  "Drúadan Forest",
  "Drúwaith Iaur",
  "Eagle's Eyrie",
  "East Harondor",
  "East Rhûn",
  "Eastemnet",
  "Eastern Brown Lands",
  "Eastern Emyn Muil",
  "Eastern Mirkwood",
  "Edoras",
  "Enedwaith",
  "Erebor",
  "Erech",
  "Ered Luin",
  "Ettenmoors",
  "Evendim",
  "Fangorn",
  "Far Harad",
  "Folde",
  "Fords of Bruinen",
  "Fords of Isen",
  "Forlindon",
  "Gap of Rohan",
  "Gladden Fields",
  "Goblin's Gate",
  "Gorgoroth",
  "Grey Havens",
  "Harlindon",
  "Helm's Deep",
  "High Pass",
  "Hollin",
  "Iron Hills",
  "Khand",
  "Lamedon",
  "Lossarnach",
  "Lórien",
  "Minas Morgul",
  "Minas Tirith",
  "Minhiriath",
  "Morannon",
  "Moria",
  "Mount Gram",
  "Mount Gundabad",
  "Narrows of the Forest",
  "Near Harad",
  "Noman-lands",
  "North Anduin Vale",
  "North Downs",
  "North Dunland",
  "North Ered Luin",
  "North Ithilien",
  "North Rhûn",
  "Northern Dorwinion",
  "Northern Mirkwood",
  "Northern Rhovanion",
  "Núrn",
  "Old Ford",
  "Old Forest",
  "Old Forest Road",
  "Orthanc",
  "Osgiliath",
  "Parth Celebrant",
  "Pelargir",
  "Rhosgobel",
  "Rivendell",
  "South Anduin Vale",
  "South Downs",
  "South Dunland",
  "South Ered Luin",
  "South Ithilien",
  "South Rhûn",
  "Southern Dorwinion",
  "Southern Mirkwood",
  "Southern Rhovanion",
  "Tharbad",
  "The Shire",
  "Tower Hills",
  "Trollshaws",
  "Umbar",
  "Vale of the Carnen",
  "Vale of the Celduin",
  "Weather Hills",
  "Westemnet",
  "West Harondor",
  "Western Brown Lands",
  "Western Emyn Muil",
  "Western Mirkwood",
  "Withered Heath",
  "Woodland Realm"
];
